kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: workload
  namespace: juju
  annotations:
    hello: world
  labels:
    app: workload
spec:
  replicas: 1
  template:
    metadata:
      name: workload
      labels:
        app: workload
    spec:
      containers:
      - name: exec-workload
        image: gcr.io/rk-playground/exec-workload
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: workload
  namespace: juju
  labels:
    app: workload
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: workload
---
